host: "localhost:8080"
clients:
  - number: 5
    client:
      rate: 5
      duration: 300
      type: 1
  - number: 5
    client:
      rate: 5
      duration: 500
      type: 1
  - number: 1
    client:
      rate: 100
      duration: 2000
      type: 2
  - number: 1
    client:
      rate: 100
      duration: 10000
      type: 3
